### ISSUE TITLE
在使用标绘工具plot的时候，鼠标和标绘点不能叠加同步移动。

### ISSUE THREAD

**Issue by mdxiaohu** [dvgis/dc-sdk#10]
描述：
使用标绘工具plot，用来绘制点标绘。
发现在2D模式下，鼠标移动，标记圆点也移动。
但是，标记圆点和鼠标位置有较大误差，不能叠加同步。
在3D模式下正常。

标绘功能没有问题，位置正确。

推测：可能是鼠标移动的时候，标记点在2D模式下沿用的是3D模式的坐标。

其他的标绘暂时没有测，可能也会存在同样的问题。

**Comment by cavencj** [comment]
你好，2D不能使用的原因是由于辅助点的高度参照的设置问题，现已解决，下个版本会更新的
