### ISSUE TITLE
历史轨迹控制器changSpeed接口设置速度不生效

### ISSUE THREAD

**Issue by AirWinger** [dvgis/dc-sdk#101]
你好, 历史轨迹控制器TrackController的changeSpeed接口无效, 设置之后速度没有变化，另外track初始化的是否考虑将duration时间改为速度参数, 在点位较少距离较短时不太好设置时间(不管距离多长都希望按照一定速度行进),要么在外面自己在根据距离在算一次,比较麻烦

**Comment by cavencj** [comment]
目前这个这个修改速度不支持了，速度的修改后期可以添加一下
