### ISSUE TITLE
加载离线地图

### ISSUE THREAD

**Issue by rwerplus** [dvgis/dc-sdk#106]
/gwc/service/wmts?tilematrix=EPSG%3A4326%3A9&layer=xxx%3AgoogleMap&style=&tilerow=144&tilecol=854&tilematrixset=EPSG%3A4326&format=image%2Fpng&service=WMTS&version=1.0.0&request=GetTile
加载服务器中的这个格式的地图怎么加载？

**Comment by cavencj** [comment]
参考createwmtsbaselayer
