### ISSUE TITLE
轨迹漫游第一视角跟随视角最后报错

### ISSUE THREAD

**Issue by lvxiong85** [dvgis/dc-sdk#107]
![image](https://user-images.githubusercontent.com/12636453/174963213-a8ae3a63-b8a9-4c6c-844c-17f72dece2b3.png)

**Comment by cavencj** [comment]
好的 我这边看下，  好像是有几率的发生

**Comment by lvxiong85** [comment]
感谢关注问题提问：
之前是使用sdk-v2.120没出现，后面用sdk-v2.140 就基本每次都出现了。
基本每次都出现，用goole 浏览器 101.0.4951.54及360浏览器都是这种情况。
不过后我切换为sdk-v2.120也存在。主要是漫游，轨迹的第一视觉，跟随视觉，播放到最后，都会出现。
----------------------------------------------------------------------------------


 
好的 我这边看下，  好像是有几率的发生

**Comment by cavencj** [comment]
好的， 我这边修复一下， 如果修复好了， 应该是下个版本发布

**Comment by cavencj** [comment]
已修复，
