### ISSUE TITLE
WARNING: Too many active WebGL contexts. Oldest context will be lost

### ISSUE THREAD

**Issue by mdxiaohu** [dvgis/dc-sdk#11]
描述：
我在使用dc-sdk做一个分屏对比的功能。
点击分屏对比按钮后，弹出对话框，然后展示2个地图（暂时是二分屏）。
关闭的时候，使用sdk里面提供的destroy()方法，销毁地图。
看似一切正常。
但是，当我多次点击对话框的时候，就会出现webgl的警告。

WARNING: Too many active WebGL contexts. Oldest context will be lost .
丢失了WebGl的上下文，然后我的主页地图（不是在弹出框创建的）就不展示了。

我尝试找了这个问题的解决方案，例如：
const canvasArr = myMap.getDom().getElementsByTagName('canvas');
for(let i=0; i<canvasArr.length; i++){
    canvasArr[i].getContext('webgl').getExtension('WEBGL_lose_context').loseContext()
}

其思路就是每次关闭的时候都清除掉webgl的上下文。
因为谷歌浏览器好像对于webgl的上下文限制是16个左右。
每次都清掉，这样原本的就不会丢失了。
但是好像没有作用。

我目前的解决方案是：不销毁掉弹出框里面创建的地图，每次关闭只是隐藏。

考虑到性能问题，所有来请教下，看是否还有其他方案。

例如说，在使用destroy方法销毁地图的时候就考虑到webGL的问题。

**Comment by cavencj** [comment]
这个问题 可以参考 https://github.com/mapbox/mapbox-gl-js/issues/7332
