### ISSUE TITLE
为什么基于加载同样的图源，地球看起来有差别呢，你们是做过什么特殊处理吗？求指教。

### ISSUE THREAD

**Issue by daisy-cyt** [dvgis/dc-sdk#136]
![717cb1d5e893a4cefb372b472a0e97c](https://user-images.githubusercontent.com/14056085/202656124-f0514dfc-1d67-4364-86e6-c9d602653b5b.png)

![766a0135d5352f71e1567d10d9c2977](https://user-images.githubusercontent.com/14056085/202656587-555212a6-d551-4850-a35d-34bd573a9305.png)

**Comment by cavencj** [comment]
高得图默认是有偏移的
