### ISSUE TITLE
缩放地图导致popup到处飘

### ISSUE THREAD

**Issue by Japheth1989** [dvgis/dc-sdk#143]
viewer.popup.setContent('<div id="Popup"></div>')
viewer.popup.setPosition(DC.Transform.transformWGS84ToCartesian(e.overlay.position))
document.getElementById('Popup').appendChild(mountPopup().$el)
为什么这种方式弹出popup在加载地形图后，缩放地图会导致popup到处飘？

**Comment by cavencj** [comment]
是因为viewer-container 没有设置position样式吗
