### ISSUE TITLE
三维分析功能

### ISSUE THREAD

**Issue by zhongshuiyuan** [dvgis/dc-sdk#15]
您好，好像sdk还不支持三维分析功能，比如开挖分析、立方分析、通视分析、可视域分析、日照分析等，请问有计划去实现这些功能吗？

**Comment by cavencj** [comment]
是的，有计划再弄，分析模块是一个单独模块(dc-analysis)，目前只有视频融合功能，后期都会出的，谢谢支持

**Comment by zhongshuiyuan** [comment]
您好，您已经出新的框架了，但是上一版本的三维分析功能还是没有，只看到视频融合及测量，请问这一版本会有吗？
