### ISSUE TITLE
高度测量是不是有bug啊

### ISSUE THREAD

**Issue by godzzh** [dvgis/dc-sdk#151]
贴地高度测量的时候，选择高度点的时候，可能会贴地，选择地面的时候，会选中空中的点

**Comment by cavencj** [comment]
好的 ，

**Comment by godzzh** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by cavencj** [comment]
测试了一下，好像没有问题， 可以看下官网最新版本的示例

**Comment by godzzh** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
