### ISSUE TITLE
npm run build 的时候报错的问题

### ISSUE THREAD

**Issue by helloliuhao0212** [dvgis/dc-sdk#16]
1 verbose cli   'build' ]
2 info using npm@6.14.5
3 info using node@v10.15.3
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle @dvgis/dc-sdk@1.9.3~prebuild: @dvgis/dc-sdk@1.9.3
6 info lifecycle @dvgis/dc-sdk@1.9.3~build: @dvgis/dc-sdk@1.9.3
7 verbose lifecycle @dvgis/dc-sdk@1.9.3~build: unsafe-perm in lifecycle true
8 verbose lifecycle @dvgis/dc-sdk@1.9.3~build: PATH: C:\Users\Liuhao\AppData\Roaming\npm\node_modules\cnpm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;H:\Work\CodeTestManage\dc-sdk-master\node_modules\.bin;H:\app\client\xxzx\product\12.1.0\client_2;H:\app\client\xxzx\product\12.1.0\client_2\bin;H:\app\Liuhao\product\11.2.0\client_2;H:\app\Liuhao\product\11.2.0\dbhome_1\bin;H:\app\xxzx\product\11.2.0\client_2;H:\app\xxzx\product\11.2.0\client_2\bin;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v1.0\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\VSShell\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio 9.0\Common7\IDE\PrivateAssemblies\;C:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\;D:\ProgramFile\JAVA\JDK\bin;D:\ProgramFile\JAVA\JDK\jre\bin;D:\ProgramFile\subsvn\bin;D:\ProgramFile\apache-tomcat-7.0.75\bin;C:\Python27;D:\ProgramFile\SVN\bin;D:\Android\android-sdk\platform-tools;D:\Android\android-sdk\tools;D:\Program Files\nodejs\;C:\Program Files (x86)\Windows Kits\8.0\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;D:\Program Files\Git\cmd;D:\Program Files\Microsoft VS Code\bin;D:\ProgramFile\apache-maven-3.6.3\bin;C:\Program Files\dotnet\;C:\Program Files (x86)\dotnet\;C:\Users\Liuhao\AppData\Roaming\npm;D:\Program Files\Microsoft VS Code\bin;C:\Users\Liuhao\.dotnet\tools;C:\Users\Liuhao\.dotnet\tools
9 verbose lifecycle @dvgis/dc-sdk@1.9.3~build: CWD: H:\Work\CodeTestManage\dc-sdk-master
10 silly lifecycle @dvgis/dc-sdk@1.9.3~build: Args: [ '/d /s /c', 'yarn run clean && webpack  --mode development' ]
11 silly lifecycle @dvgis/dc-sdk@1.9.3~build: Returned: code: 2  signal: null
12 info lifecycle @dvgis/dc-sdk@1.9.3~build: Failed to exec build script
13 verbose stack Error: @dvgis/dc-sdk@1.9.3 build: `yarn run clean && webpack  --mode development`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\Liuhao\AppData\Roaming\npm\node_modules\cnpm\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\Liuhao\AppData\Roaming\npm\node_modules\cnpm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid @dvgis/dc-sdk@1.9.3
15 verbose cwd H:\Work\CodeTestManage\dc-sdk-master
16 verbose Windows_NT 6.1.7601
17 verbose argv "D:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Liuhao\\AppData\\Roaming\\npm\\node_modules\\cnpm\\node_modules\\npm\\bin\\npm-cli.js" "--userconfig=C:\\Users\\Liuhao\\.cnpmrc" "--disturl=https://npm.taobao.org/mirrors/node" "--registry=https://r.npm.taobao.org" "run" "build"
18 verbose node v10.15.3
19 verbose npm  v6.14.5
20 error code ELIFECYCLE
21 error errno 2
22 error @dvgis/dc-sdk@1.9.3 build: `yarn run clean && webpack  --mode development`
22 error Exit status 2
23 error Failed at the @dvgis/dc-sdk@1.9.3 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]
![image](https://user-images.githubusercontent.com/52664357/106438062-ef7e8500-64b0-11eb-94f2-c0aeff07ee03.png)

**Comment by cavencj** [comment]
这是node版本问题。然后将yarn.lock的删除，重新安装，我编译的机器是mac
