### ISSUE TITLE
npm run dev 报错，是node版本问题吗？需要哪个版本？

### ISSUE THREAD

**Issue by alice2108** [dvgis/dc-sdk#160]
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'D:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'D:\\ProgramFiles\\nodejs\\node_global\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dev'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v13.14.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle @dvgis/dc-sdk@3.1.0~predev: @dvgis/dc-sdk@3.1.0
6 info lifecycle @dvgis/dc-sdk@3.1.0~dev: @dvgis/dc-sdk@3.1.0
7 verbose lifecycle @dvgis/dc-sdk@3.1.0~dev: unsafe-perm in lifecycle true
8 verbose lifecycle @dvgis/dc-sdk@3.1.0~dev: PATH: D:\ProgramFiles\nodejs\node_global\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;E:\repository\2021\DEsdk\dc-sdk-master0817\dc-sdk-master\node_modules\.bin;D:\Program Files\Java\jdk1.8.0_181\bin;D:\Program Files\Java\jdk-1.8.0_181\bin;D:\Program Files\Java\jdk-1.8.0_181\jre\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Program Files (x86)\AMD\ATI.ACE\Core-Static;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files\TortoiseSVN\bin;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files (x86)\Microsoft ASP.NET\ASP.NET Web Pages\v1.0\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Windows\System32\WindowsPowerShell\v1.0\;D:\OSG\OpenSceneGraph\bin;D:\OSG\osgEarth\vs2010\bin\Debug;D:\OSG\osgEarth\vs2010\bin\Release;C:\Program Files\Common Files\Autodesk Shared\;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Users\wangnian\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;D:\AndroidSDK\platform-tools;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\VSShell\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio 9.0\Common7\IDE\PrivateAssemblies\;C:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\;D:\ProgramFiles\nodejs\node_global;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;D:\A_WorkSpace\bxf\Python\Python2.7.15\Lib\site-packages\selenium\webdriver\chrome;D:\A_WorkSpace\bxf\instantclient-basic-windows.x64-12.2.0.1.0\instantclient_12_2;D:\Program Files\Git\cmd;D:\Program Files\Microsoft VS Code\bin;D:\bxfSoftSetup\ffmpeg-20190426-f857753-win64-static\bin;D:\AndroidSDK\platform-tools;D:\Program Files\Redis\;D:\bxfSoftSetup\mysql-5.7.26-winx64;D:\bxfSoftSetup\MATLAB\MATLAB Runtime\v93\runtime\win64;C:\Program Files\OpenSSH-Win64;D:\bxfSoftSetup\MATLAB\MATLAB Runtime\v912\runtime\win64;E:\Apro\nginx-1.19.0\nginx-1.19.0;C:\Program Files (x86)\PuTTY\;D:\Program Files\nodejs\;D:\bxfSoftSetup\Python\Python36\Scripts\;D:\bxfSoftSetup\Python\Python36\;C:\RailsInstaller\Git\cmd;C:\RailsInstaller\Ruby2.2.0\bin;D:\Program Files\Microsoft VS Code\bin;C:\Users\wangnian\AppData\Roaming\npm;;C:\Users\bxf\AppData\Roaming\搜狐影音\6.5.5.0;C:\Users\bxf\AppData\Roaming\npm
9 verbose lifecycle @dvgis/dc-sdk@3.1.0~dev: CWD: E:\repository\2021\DEsdk\dc-sdk-master0817\dc-sdk-master
10 silly lifecycle @dvgis/dc-sdk@3.1.0~dev: Args: [ '/d /s /c', 'gulp dev' ]
11 silly lifecycle @dvgis/dc-sdk@3.1.0~dev: Returned: code: 1  signal: null
12 info lifecycle @dvgis/dc-sdk@3.1.0~dev: Failed to exec dev script
13 verbose stack Error: @dvgis/dc-sdk@3.1.0 dev: `gulp dev`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (D:\ProgramFiles\nodejs\node_global\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (D:\ProgramFiles\nodejs\node_global\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1026:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid @dvgis/dc-sdk@3.1.0
15 verbose cwd E:\repository\2021\DEsdk\dc-sdk-master0817\dc-sdk-master
16 verbose Windows_NT 6.1.7601
17 verbose argv "D:\\Program Files\\nodejs\\node.exe" "D:\\ProgramFiles\\nodejs\\node_global\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
18 verbose node v13.14.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error @dvgis/dc-sdk@3.1.0 dev: `gulp dev`
22 error Exit status 1
23 error Failed at the @dvgis/dc-sdk@3.1.0 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by cavencj** [comment]
可以试下 16的版本

**Comment by alice2108** [comment]
谢谢您的来件，祝您工作顺利，生活美满。
