### ISSUE TITLE
静态资源文件 404

### ISSUE THREAD

**Issue by 94ashui** [dvgis/dc-sdk#185]
静态资源文件 404
这是我的路由路径：
![image](https://github.com/dvgis/dc-sdk/assets/89236888/890dbc23-2565-477e-9a52-a927c92ed7c0)
刷新页面的时候这两个文件路径请求地址不对：
![image](https://github.com/dvgis/dc-sdk/assets/89236888/bac5c8f4-dadd-48ce-a02d-d79b81710d17)

_Originally posted by @94ashui in https://github.com/dvgis/dc-sdk/issues/8#issuecomment-2138531014_

**Comment by cavencj** [comment]
有资源文件吗， 不是200吗

**Comment by 94ashui** [comment]
不是，因为加上了plans这个路径，实际上这个要去掉的。
