### ISSUE TITLE
gac-geo.googlecnapps.cn域名获取图片 404

### ISSUE THREAD

**Issue by blankuserr** [dvgis/dc-sdk#188]
使用 DC.TerrainFactory.createUrlTerrain({
        url: 'http://data.marsgis.cn/terrain',
      }) 创建视图，从 gac-geo.googlecnapps.cn 请求静态资源文件提示404, 有无解决办法

**Comment by cavencj** [comment]
这个第三方的数据服务，可以自己使用dem数据切地形瓦片数据，
