### ISSUE TITLE
getAzimuth这个函数的思路是什么，为什么StarPnt(0,0),endPnt（1.0），最后方位角是180度呢

### ISSUE THREAD

**Issue by moxuanzhu** [dvgis/dc-sdk#201]
/**
   * @param startPnt
   * @param endPnt
   * @returns {number}
   */
  static getAzimuth(startPnt, endPnt) {
    let azimuth
    let angle = Math.asin(
      Math.abs(endPnt[1] - startPnt[1]) / this.distance(startPnt, endPnt)
    )
    if (endPnt[1] >= startPnt[1] && endPnt[0] >= startPnt[0])
      azimuth = angle + Math.PI
    else if (endPnt[1] >= startPnt[1] && endPnt[0] < startPnt[0])
      azimuth = TWO_PI - angle
    else if (endPnt[1] < startPnt[1] && endPnt[0] < startPnt[0]) azimuth = angle
    else if (endPnt[1] < startPnt[1] && endPnt[0] >= startPnt[0])
      azimuth = Math.PI - angle
    return azimuth
  }
getAzimuth这个函数的思路是什么，为什么StarPnt(0,0),endPnt（1.0），最后方位角是180度呢，谢谢！

**Comment by cavencj** [comment]
这部分代码也是从二维复制过来的
