### ISSUE TITLE
资源过载时三维不加载： The source image could not be decoded.

### ISSUE THREAD

**Issue by wujianyouhun** [dvgis/dc-sdk#203]
资源加载量大或者页面卡顿，刷新的时候三维不加载。
/dc-sdk/resources/Workers/createVerticesFromQuantizedTerrainMesh.js
libs/dc-sdk/resources/Workers/createVerticesFromQuantizedTerrainMesh.js:1 Failed to load module script: The server responded with a non-JavaScript MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.
![Uploading 微信截图_20241121153134.png…]()

**Comment by cavencj** [comment]
资源地址不对

**Comment by wujianyouhun** [comment]
是的老师，是不是库引用错了

**Comment by cavencj** [comment]
最终定位项目配置问题， 已解决
