### ISSUE TITLE
模型着色器渲染错误

### ISSUE THREAD

**Issue by MrChen0913** [dvgis/dc-sdk#207]
着色器代码
fragmentShaderText：`
          void fragmentMain(FragmentInput fsInput, inout czm_modelMaterial material) {
            float _baseHeight = 0.0; // 物体的基础高度，需要修改成一个合适的建筑基础高度
            float _heightRange = 60.0; // 高亮的范围(_baseHeight ~ _baseHeight + _      heightRange) 默认是 0-60米
            float _glowRange = 300.0; // 光环的移动范围(高度)
            float vtxf_height = fsInput.attributes.positionMC.z-_baseHeight;
            float vtxf_a11 = fract(czm_frameNumber / 120.0) * 3.14159265 * 2.0;
            float vtxf_a12 = vtxf_height / _heightRange + sin(vtxf_a11) * 0.1;
            material.diffuse*= vec3(vtxf_a12, vtxf_a12, vtxf_a12);
            float vtxf_a13 = fract(czm_frameNumber / 360.0);
            float vtxf_h = clamp(vtxf_height / _glowRange, 0.0, 1.0);
            vtxf_a13 = abs(vtxf_a13 - 0.5) * 2.0;
            float vtxf_diff = step(0.005, abs(vtxf_h - vtxf_a13));
            material.diffuse += material.diffuse * (1.0 - vtxf_diff);
          }    
        `
期望效果
![025e8495abd61b356adf10d6e6c5f98](https://github.com/user-attachments/assets/4cfdea67-d3cc-4dba-b84a-a6a04363a0ff)
实际效果
![847a8e780cd3369988596be6d057cff](https://github.com/user-attachments/assets/01ed6f9f-0c9c-4e14-bf61-035df7d624af)

**Comment by cavencj** [comment]
是不是走的问题

**Comment by MrChen0913** [comment]
大神 请问怎么解决 看高亮线也是倾斜的
![image](https://github.com/user-attachments/assets/e6a27899-fe3b-42f2-b1ad-a61c257ec86b)

**Comment by cavencj** [comment]
你看看 是那个轴朝上， 就该那个轴的值

**Comment by MrChen0913** [comment]
感谢 刚刚着色器改为fsInput.attributes.positionMC.y就可以了
