### ISSUE TITLE
Cannot import @dvgis/dc-sdk/dist/dc.core.min in Create-react-app

### ISSUE THREAD

**Issue by JoeyKo** [dvgis/dc-sdk#49]
使用create-react-app创建项目，在项目中引入dc.core报错
```javasctipr
import DcCore from '@dvgis/dc-sdk/dist/dc.core.min'
````
![image](https://user-images.githubusercontent.com/16659637/125898108-04c5ef72-ca0c-4bfd-834c-1b14cea013a7.png)

**Comment by JoeyKo** [comment]
引入dc.core报错
```javasctipr
import DcCore from '@dvgis/dc-sdk/dist/dc.core.min'
````

**Comment by cavencj** [comment]
是的， 应该内部的webpack配置不支持， 建议使用 https://github.com/dvgis/dc-react
