### ISSUE TITLE
集成的Echart示例在地球俯仰视角低的情况下会错误的显示，并没有被遮挡

### ISSUE THREAD

**Issue by abigstupidbear** [dvgis/dc-sdk#55]
![image](https://user-images.githubusercontent.com/29300501/130308343-4cf605e8-26b0-4307-a330-aee3ff9689eb.png)

**Comment by abigstupidbear** [comment]
这个是不准备修复吗？

**Comment by cavencj** [comment]
已修复 将于下个版本发布

**Comment by abigstupidbear** [comment]
牛逼
