### ISSUE TITLE
DIV图层低俯仰下并没有被遮挡

### ISSUE THREAD

**Issue by abigstupidbear** [dvgis/dc-sdk#56]

**Comment by cavencj** [comment]
你好 我这边测试一下，是有覆盖的，对于一个DIv ，开发后期是完全可以自定css样式进行相关设置的，
<img width="914" alt="1" src="https://user-images.githubusercontent.com/33321375/130308968-f5f9afe5-2c85-4819-aab1-97ffd310ed8e.png">

**Comment by abigstupidbear** [comment]
您好 不是这个意思 是我再高视角的时候俯仰 标签跑到地球后面的时候 应该看不到，实际上他是看到的。问题就像今天我提的 echart的情况是一样的

**Comment by cavencj** [comment]
这个问题会在下个版本中修复
