### ISSUE TITLE
Fragment shader failed to compile

### ISSUE THREAD

**Issue by zhongshuiyuan** [dvgis/dc-sdk#6]
有些模型加载会报错，
ERROR: 0:6: '=' : dimension mismatch

ERROR: 0:6: 'assign' : cannot convert from 'const highp float' to 'FragColor mediump 4-component vector of float'

**Comment by cavencj** [comment]
@有些模型材质是无法识别的，我也遇到了，所以需要将模型材质修改为Cesium的识别的材质,可以查看官方文档
https://cesium.com/docs/cesiumjs-ref-doc/Model.html?classFilter=Model
