### ISSUE TITLE
关于 百度或谷歌离线瓦片的加载

### ISSUE THREAD

**Issue by 156704883** [dvgis/dc-sdk#62]
let baselayer_img = DC.ImageryLayerFactory.createBaiduImageryLayer({
          style:'normal',
          url:"http://x.x.x.x/tile/?qt=tile&x={x}&y={y}&z={z}&styles=pl"     这个参数是无效的
          //crs:'WGS84'
      })

**Comment by 156704883** [comment]
如何自定义 这个 瓦片的 url ,用于本地离线地图的加载呢

**Comment by cavencj** [comment]
目前使用的url时互联网上默认的 ， 如果要使用本地，可以将
let baselayer_img = DC.ImageryLayerFactory.createBaiduImageryLayer({
//crs:'WGS84'
})
baselayer_img._url = http://x.x.x.x/tile/?qt=tile&x={x}&y={y}&z={z}&styles=pl  进行强制替换
