### ISSUE TITLE
Module parse failed: Unexpected token

### ISSUE THREAD

**Issue by nightmaring** [dvgis/dc-sdk#63]
操作系统：windows 10

不好意思，我知道这个问题和dc-sdk无关，但是我找了一天，并没发现问题，所以想请教一下，如果刚好有碰到并且已经解决的，麻烦告知下，谢谢！

操作流程：通过yarn install 安装依赖之后，运行打包一直提示“Module parse failed: Unexpected token”，仔细看了下代码，将问题定位在可选链式操作符上，查看库中common.js，发现babel配置没问题，并且依赖中也有处理可选链式操作符文件

**Comment by cavencj** [comment]
请问你这个是编译框架造成的码，方便的话可以截个图，或者加入群聊呢

**Comment by nightmaring** [comment]
> 说明你这是编译框架造成的码，方便的话可以截个图，或者加入群聊呢

![image](https://user-images.githubusercontent.com/18131312/131307749-8401d55e-b090-452e-9e96-c286bcc3cb09.png)

**Comment by cavencj** [comment]
尝试升级一下node的版本， 然后删除yarn.lock 和 node_modules , 重新安装依赖

**Comment by nightmaring** [comment]
> 尝试升级一下node的版本，然后删除yarn.lock和node_modules，重新安装依赖
之前尝试过v16.5.0
目前版本是v14.17.5
package.json中node-sass：v5.0.0要求node必须要是14，超过14会报错

**Comment by cavencj** [comment]
可以将node-sass 移除掉

**Comment by cavencj** [comment]
我这边测试一下，我的node 版本是v12.18.4，然后删除yarn.lock了 和 node_modules ，是可以打包的

**Comment by nightmaring** [comment]
我重写下载了一次，什么都不改，也没有删除yarn.lock，直接yarn install，打包没有报错，很奇怪

**Comment by nightmaring** [comment]
第一次下载的时候本地node版本是16.5.0，然后node-sass报错，分析发现需要使用v14.x.x，改为14.17.5之后，打包就出现了这个错误，然后刚刚再次下载dc-sdk，直接用14.17.5去运行，无任何错误。自认为第一次操作没有任何问题且第一次下载和第二次下载运行的node环境也相同，很奇怪

**Comment by cavencj** [comment]
有可能是yarn.lock的问题，我的yarn.lock 用的macos系统的

**Comment by nightmaring** [comment]
我刚刚又测试了一下，yarn.lock无关。

我这边将dc-sdk代码放入了vue的node_modules，然后给dc-sdk安装依赖并打包，打包的时候就出现了这个问题，目前还是不知道为什么会这样
