### ISSUE TITLE
代码提示

### ISSUE THREAD

**Issue by abigstupidbear** [dvgis/dc-sdk#69]
你好，我在使用webstrom 或vscode 开发时，使用打包的库，发现无法使用代码提示功能
请问是打包配置的问题吗

**Comment by cavencj** [comment]
目前还未支持,打包时未发布源码结构

**Comment by abigstupidbear** [comment]
建议支持一下 在用框架写代码的时候没有提示还是很费劲的😀

**Comment by cavencj** [comment]
已将这个移到讨论组中了，请关注后续更新
