### ISSUE TITLE
const { Cesium } = DC.Namesapce 官网文档拼写错误

### ISSUE THREAD

**Issue by mdxiaohu** [dvgis/dc-sdk#7]
你好，我发现本项目官方文档，有一个小错误，可能会带来不必要的麻烦。

例如官网示例：
开发时如果需要 Cesium 的内部接口可以通过 const { Cesium } = DC.Namesapce 获取 Cesium。
事实上，工程里面正确的引入应该是：
开发时如果需要 Cesium 的内部接口可以通过 const { Cesium } = DC.Namespace获取 Cesium。

我是在自己扩展DC方法时，按照文档里面的方法，进行编写。
但Cesium一直没有拿到值，经过几次调试后，发现原来是单词拼写错误。

**Comment by cavencj** [comment]
好的 谢谢，我这边更新一下

**Comment by cavencj** [comment]
最新文档已发布
