### ISSUE TITLE
DynimicBillboard的addPosition怎么会跳一下？

### ISSUE THREAD

**Issue by Japheth1989** [dvgis/dc-sdk#77]
更新广告牌位置时利用addPosition会跳到某个位置然后平滑移动

**Comment by Japheth1989** [comment]
viewer = new DC.Viewer('viewer-container')
    let baselayer = DC.ImageryLayerFactory.createBaiduImageryLayer({
       style:"dark",
       crs:'WGS84'
    })
    viewer.addBaseLayer(baselayer)
    let layer = new DC.DynamicLayer('layer').addTo(viewer)
    for(let i = 0; i<50; i++){
      let model = new DC.DynamicModel(generatePosition(1)[0],'examples/data/model/qiche.gltf')
      model.setStyle({
        scale:10
      })
      layer.addOverlay(model)
    }
    setInterval(()=>{
      layer.getOverlays().forEach(item=>{
        item.addPosition(generatePosition(1)[0],5)
      })
    },10000)

两个间隔时间不一致会产生跳跃，请问是什么问题？谢谢

**Comment by Japheth1989** [comment]
后台定时上报实时位置，然后地图实现广告牌的平滑移动。上报间隔时间跟移动时间不一致导致跳跃，请问是什么问题？是不是源码有bug？希望能帮忙解决。谢谢。

**Comment by cavencj** [comment]
你好 ，我这边测试一下 ，进行源码的调整，依旧存在这个问题，这个问题应该是Cesium取样的位置属性的问题

**Comment by Japheth1989** [comment]
大佬，这个能有办法解决吗？现在态势监控卡在这，能否帮忙改改？谢谢。

**Comment by cavencj** [comment]
目前是将间隔时间设置成一样的

**Comment by Japheth1989** [comment]
大佬，这个能有办法解决吗？现在态势监控卡在这，能否帮忙改改？谢谢。

**Comment by Japheth1989** [comment]
设置成一样的话，第一次也会跳一下，后面就不会了。这样有种情况不好处理（比如监控人走动，下面上报是20s，然后在地图上基本看不到移动效果）

**Comment by cavencj** [comment]
或者你试一下轨迹回放的功能，那个是点位更新是按照每一帧算的
