### ISSUE TITLE
您好，我在使用Vue开发中，创建地图遇到了一个链接404问题。

### ISSUE THREAD

**Issue by mdxiaohu** [dvgis/dc-sdk#8]
在Vue工程里，使用DC-Sdk创建地图的时候，会出现一个url错误。

引入说明：在Vue工程里，我并没有通过npm引入，而是通过将DC-Sdk工程打包为js引入到项目中，因为这样，方便我之后对sdk进行扩展。

例如：
http://192.168.0.32:8000/pictureForestry/libs/dc-sdk/resources/Assets/approximateTerrainHeights.json 404 (Not Found)
http://192.168.0.32:8000/pictureForestry/libs/dc-sdk/resources/Assets/IAU2006_XYS/IAU2006_XYS_16.json 404 (Not Found)
这两个json文件，好像是动态创建的，没有json文件底图就不展示，地图区域展示为全黑色。

事实上，正确的链接地址应该为：
http://192.168.0.32:8000/libs/dc-sdk/resources/Assets/approximateTerrainHeights.json
http://192.168.0.32:8000/libs/dc-sdk/resources/Assets/IAU2006_XYS/IAU2006_XYS_16.json

推测：
DC-Sdk在创建地图的时候，会加上Vue的路由地址pictureForestry。

请问如何修改，才能让DC-sdk拿到正确的地址？

**Comment by mdxiaohu** [comment]
我查看了DC-Sdk工程的源码，已经修改好了。

**Comment by njueyupeng** [comment]
你好，修改的commit是哪一个？我有一个工程固化了版本，需要对应修改一下

**Comment by mdxiaohu** [comment]
我不是很清楚你的需求，要是用1.x或者2.x的话，可以在项目tags中找对应的包。
固化版本就建议直接找到对应时期的源码，打包后，本地引入到项目工程中。

**Comment by njueyupeng** [comment]
【自动回复】您好，我已收到您的邮件。

**Comment by njueyupeng** [comment]
### 2.2.3版本及之后版本解决办法：
更改baseurl,设置为正确的资源路径，默认为相对路径'./libs/dc-sdk/resources/‘
`DC.baseUrl='/libs/dc-sdk/resources/'`

### 2.2.3之前版本解决办法：
直接设置Cesium的资源路径
```
const { Cesium } = DC.Namespace;
const basePath = process.env.NODE_ENV === 'production' ? '/' : '/'
Cesium.buildModuleUrl.setBaseUrl(`${basePath}libs/dc-sdk/resources/`)
```

**Comment by 94ashui** [comment]
这个问题在最新得版本上面也复现了。
这是我得路由路径：
![image](https://github.com/dvgis/dc-sdk/assets/89236888/890dbc23-2565-477e-9a52-a927c92ed7c0)
刷新页面的时候这两个文件路径请求地址不对：
![image](https://github.com/dvgis/dc-sdk/assets/89236888/bac5c8f4-dadd-48ce-a02d-d79b81710d17)
