### ISSUE TITLE
标绘过程中转动地球， 会导致绘制的线和点不在同一区域

### ISSUE THREAD

**Issue by Zeng5475** [dvgis/dc-sdk#94]
![1650687829](https://user-images.githubusercontent.com/45525582/164876520-d447898c-b067-4586-8696-e6fc63b8318a.jpg)

**Comment by Zeng5475** [comment]
目前已经在源码中添加，这句代码， 已经解决
![image](https://user-images.githubusercontent.com/45525582/164887889-40b2ca8a-5e74-4f70-9d49-4d4fac1b74bb.png)

**Comment by cavencj** [comment]
好的 我这边看下
